fixtures:
  repositories:
    'stdlib':  'git://github.com/puppetlabs/puppetlabs-stdlib'
    'apt':
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref:  '1.4.0'
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'apache':
      repo: 'git://github.com/puppetlabs/puppetlabs-apache'
      ref: '1.4.1'
    'concat':
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      ref: '2.1.0'

  symlinks:
    'ceph': "#{source_dir}"
